language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t robesantororobesantoro/docker_rest -f Dockerfile .

script:
  - docker run robesantororobesantoro/docker_rest ./mvnw test

after_success:
  - docker build -t robesantororobesantoro/docker_rest -f Dockerfile_prod .

  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push robesantororobesantoro/docker_rest