language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t robesantororobesantoro/docker_rest -f Dockerfile .
  - chmod +x mvnw  

script:
  - docker run robesantororobesantoro/docker_rest ./mvnw test