language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t robesantororobesantoro/docker_rest -f Dockerfile .

script:
  - docker run robesantororobesantoro/docker_rest ./mvnw test

after_success:
  - docker run robesantororobesantoro/docker_rest ./mvnw package -DskipTests